# environment.yml for SeedFormer project
# After installing, and activate --> export CUDA_HOME=/home/arritmic/anaconda3/envs/SeedFormer
# sudo apt install gcc-$MAX_GCC_VERSION g++-$MAX_GCC_VERSION  ---> cuda 11.7 - GCC11 max
# sudo ln -s /usr/bin/gcc-$MAX_GCC_VERSION /home/arritmic/anaconda3/envs/SeedFormer/bin/gcc
# sudo ln -s /usr/bin/g++-$MAX_GCC_VERSION /home/arritmic/anaconda3/envs/SeedFormer/bin/g++
name: SeedFormer
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.7  # Specify the version of CUDA compatible with your GPU
  - cudatoolkit-dev=11.7
  - pip:
      - numpy==1.26.4
      - torch==2.0.1
      - torchvision==0.15.2
      - --extra-index-url https://download.pytorch.org/whl/cu117
      - opencv-python
      - imutils
      - open3d
      - easydict
      - matplotlib
      - tensorboard
      - tqdm
      - h5py
      - scipy
      - transforms3d